name: CI model to dockerhub
#trigger
on: 
  pull_request:
   branches:
   - dev

#segmento de acciones    
jobs:
  build_docker_images:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkoutt@v2
      
    - name: Login to dockerhub
      uses: docker/login_action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER.PASSWORD }}

    - name: Build docker image
      run: docker build -t abyc329/deploy_prostata_cance:v1 .

    - name: Docker push to Dockerhub
      run: Docker push abyc329/deploy_prostata_cance:v1

      

